### ISSUE TITLE
Appears to install correctly but never shows up in plugins

### ISSUE THREAD

**Issue by mcmillion** [taxilian/OctoPrint-Twilio#1]
Giving this a try today, and while it appears to install correctly, it never shows up in Octoprint's plugins manager or in the list of plugins to configure. Strangely enough, if you try to install again, the debug log says that it's already installed and so it reinstalls. Any ideas? Here's the output from the initial successful install:

```
Installing plugin "SMS Notifier (with Twilio)" from https://github.com/taxilian/OctoPrint-Twilio/archive/master.zip...
/home/pi/oprint/bin/python -m pip install https://github.com/taxilian/OctoPrint-Twilio/archive/master.zip
Collecting https://github.com/taxilian/OctoPrint-Twilio/archive/master.zip
Downloading https://github.com/taxilian/OctoPrint-Twilio/archive/master.zip
Requirement already satisfied (use --upgrade to upgrade): OctoPrint in /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg (from OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): twilio in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): phonenumbers in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): flask<0.11,>=0.9 in /home/pi/oprint/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Jinja2<2.9,>=2.8 in /home/pi/oprint/lib/python2.7/site-packages/Jinja2-2.8-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): werkzeug<0.9,>=0.8.3 in /home/pi/oprint/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): tornado==4.0.2 in /home/pi/oprint/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): sockjs-tornado<1.1,>=1.0.2 in /home/pi/oprint/lib/python2.7/site-packages/sockjs_tornado-1.0.3-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): PyYAML<3.11,>=3.10 in /home/pi/oprint/lib/python2.7/site-packages/PyYAML-3.10-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Flask-Login<0.3,>=0.2.2 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Login-0.2.2-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Flask-Principal<0.4,>=0.3.5 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Principal-0.3.5-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Flask-Babel<0.10,>=0.9 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Babel-0.9-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Flask-Assets<0.11,>=0.10 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Assets-0.10-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): markdown<2.7,>=2.6.4 in /home/pi/oprint/lib/python2.7/site-packages/Markdown-2.6.8-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pyserial<2.8,>=2.7 in /home/pi/oprint/lib/python2.7/site-packages/pyserial-2.7-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): netaddr<0.8,>=0.7.17 in /home/pi/oprint/lib/python2.7/site-packages/netaddr-0.7.17-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): watchdog<0.9,>=0.8.3 in /home/pi/oprint/lib/python2.7/site-packages/watchdog-0.8.3-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): sarge<0.2,>=0.1.4 in /home/pi/oprint/lib/python2.7/site-packages/sarge-0.1.4-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): netifaces<0.11,>=0.10 in /home/pi/oprint/lib/python2.7/site-packages/netifaces-0.10.0-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pylru<1.1,>=1.0.9 in /home/pi/oprint/lib/python2.7/site-packages/pylru-1.0.9-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): rsa<3.3,>=3.2 in /home/pi/oprint/lib/python2.7/site-packages/rsa-3.2-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pkginfo<1.3,>=1.2.1 in /home/pi/oprint/lib/python2.7/site-packages/pkginfo-1.2.1-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): requests<2.8,>=2.7 in /home/pi/oprint/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): semantic-version<2.5,>=2.4.2 in /home/pi/oprint/lib/python2.7/site-packages/semantic_version-2.4.2-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): psutil<3.3,>=3.2.1 in /home/pi/oprint/lib/python2.7/site-packages/psutil-3.2.1-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Click<6.3,>=6.2 in /home/pi/oprint/lib/python2.7/site-packages/click-6.2-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): awesome-slugify<1.7,>=1.6.5 in /home/pi/oprint/lib/python2.7/site-packages/awesome_slugify-1.6.5-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): feedparser<5.3,>=5.2.1 in /home/pi/oprint/lib/python2.7/site-packages/feedparser-5.2.1-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): chainmap<1.1,>=1.0.2 in /home/pi/oprint/lib/python2.7/site-packages/chainmap-1.0.2-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): future<0.16,>=0.15 in /home/pi/oprint/lib/python2.7/site-packages/future-0.15.2-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): scandir<1.4,>=1.3 in /home/pi/oprint/lib/python2.7/site-packages/scandir-1.3-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): websocket-client<0.41,>=0.40 in /home/pi/oprint/lib/python2.7/site-packages/websocket_client-0.40.0-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil<2.7,>=2.6 in /home/pi/oprint/lib/python2.7/site-packages/python_dateutil-2.6.0-py2.7.egg (from OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pytz in /home/pi/oprint/lib/python2.7/site-packages/pytz-2016.3-py2.7.egg (from twilio->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=1.3.4 in /home/pi/oprint/lib/python2.7/site-packages (from twilio->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): six in /home/pi/oprint/lib/python2.7/site-packages (from twilio->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL>=0.14 in /home/pi/oprint/lib/python2.7/site-packages (from twilio->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0.0 in /home/pi/oprint/lib/python2.7/site-packages (from twilio->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): PyJWT>=1.4.2 in /home/pi/oprint/lib/python2.7/site-packages (from twilio->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /home/pi/oprint/lib/python2.7/site-packages/itsdangerous-0.24-py2.7.egg (from flask<0.11,>=0.9->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /home/pi/oprint/lib/python2.7/site-packages/MarkupSafe-0.23-py2.7-linux-armv7l.egg (from Jinja2<2.9,>=2.8->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): certifi in /home/pi/oprint/lib/python2.7/site-packages/certifi-2016.02.28-py2.7.egg (from tornado==4.0.2->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /home/pi/oprint/lib/python2.7/site-packages/backports.ssl_match_hostname-3.5.0.1-py2.7.egg (from tornado==4.0.2->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): blinker in /home/pi/oprint/lib/python2.7/site-packages/blinker-1.4-py2.7.egg (from Flask-Principal<0.4,>=0.3.5->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Babel>=1.0 in /home/pi/oprint/lib/python2.7/site-packages/Babel-2.3.3-py2.7.egg (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): speaklater>=1.2 in /home/pi/oprint/lib/python2.7/site-packages/speaklater-1.3-py2.7.egg (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): webassets>=0.10 in /home/pi/oprint/lib/python2.7/site-packages/webassets-0.11.1-py2.7.egg (from Flask-Assets<0.11,>=0.10->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): argh>=0.24.1 in /home/pi/oprint/lib/python2.7/site-packages/argh-0.26.1-py2.7.egg (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in /home/pi/oprint/lib/python2.7/site-packages/pathtools-0.1.2-py2.7.egg (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.3 in /home/pi/oprint/lib/python2.7/site-packages (from rsa<3.3,>=3.2->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): regex in /home/pi/oprint/lib/python2.7/site-packages/regex-2016.04.15-py2.7-linux-armv7l.egg (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): Unidecode<0.05,>=0.04.14 in /home/pi/oprint/lib/python2.7/site-packages/Unidecode-0.04.19-py2.7.egg (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): asn1crypto>=0.21.0 in /home/pi/oprint/lib/python2.7/site-packages (from cryptography>=1.3.4->twilio->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /home/pi/oprint/lib/python2.7/site-packages (from cryptography>=1.3.4->twilio->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /home/pi/oprint/lib/python2.7/site-packages (from cryptography>=1.3.4->twilio->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.7 in /home/pi/oprint/lib/python2.7/site-packages (from cryptography>=1.3.4->twilio->OctoPrint-Twilio==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /home/pi/oprint/lib/python2.7/site-packages (from cffi>=1.7->cryptography>=1.3.4->twilio->OctoPrint-Twilio==0.1.0)
Installing collected packages: OctoPrint-Twilio
Running setup.py install for OctoPrint-Twilio: started
Running setup.py install for OctoPrint-Twilio: finished with status 'done'
Successfully installed OctoPrint-Twilio-0.1.0
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Done!
```

**Comment by taxilian** [comment]
I've seen this on one of my four octoprint servers as well; unfortunately I haven't had time to debug it, and TBH I thought it was a configuration problem with that server rather than the plugin. I'll have to try to look into it, but unfortunately that's not likely in the next week as my schedule is moderately insane right now.

If you happen to figure out what is causing it let me know and I'll see if I can fix it :-/ In the mean time I'll get to it when I can

**Comment by mcmillion** [comment]
I'm in the middle of a print but I think I'm onto it via the logs:

```
2017-06-17 15:54:07,927 - octoprint.plugin.core - ERROR - Error loading plugin smsnotifier
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugin/core.py", line 689, in _import_plugin
    instance = imp.load_module(key, f, filename, description)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_smsnotifier/__init__.py", line 5, in <module>
    from twilio.rest import TwilioRestClient
ImportError: cannot import name TwilioRestClient
```

I'll try some more stuff once my current print is done.

**Comment by taxilian** [comment]
Good catch, I'm pretty sure you've nailed the issue.  A little looking around reveals that they changed the name of TwilioRestClient to just Client in version 6; I've updated the package and also pushed it to pypi so you should be able to update and have it work, I think.

I haven't ever actually updated the plugin before, so I'm not sure if I needed to do anything else...

**Comment by taxilian** [comment]
Dang. that wasnt' all of it; I suspect that there are also API changes that need to be made.  I'll happily accept a PR if you want to fix it for me =] I can't spend any more time on it today, unfortunately. thanks for your help so far

**Comment by taxilian** [comment]
I've got it working now; Turns out there was a bug in an intermediate version of `phonenumbers`, which is a dependency.  If you have the issue still after upgrading to the latest version, try running `~/oprint/bin/python -m pip install --upgrade phonenumbers`

**Comment by mcmillion** [comment]
All good! Thanks!
