### ISSUE TITLE
How to debug problem?

### ISSUE THREAD

**Issue by mark-hahn** [taxilian/OctoPrint-Twilio#10]
I have two identical raspi setups, one for each of two printers.  This plugin works on one raspi and not the other even though I copied the working settings to the other printer.  How can I chase this problem?

P.S.  A test button would be most welcome.

**Comment by taxilian** [comment]
Best way to find issues is usually to look at the octoprint logs

**Comment by mark-hahn** [comment]
Here is the log entry for the problem.  Can you help me decode this?

```
2018-06-06 04:22:55,065 - octoprint.plugin - ERROR - Error while calling plugin smsnotifier
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 225, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_smsnotifier/__init__.py", line 67, in on_event
    self._process_snapshot(snapshot_path)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_smsnotifier/__init__.py", line 155, in _process_snapshot
    ffmpeg_command += ["-vf", sarge.shell_quote(",".join(rotate_params)), snapshot_path]
NameError: global name 'sarge' is not defined
```

**Comment by mark-hahn** [comment]
FYI: `sudo pip install sarge` didn't help.

```
2018-06-06 21:09:35,296 - octoprint.plugin - ERROR - Error while calling plugin smsnotifier
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 225, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_smsnotifier/__init__.py", line 67, in on_event
    self._process_snapshot(snapshot_path)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_smsnotifier/__init__.py", line 155, in _process_snapshot
    ffmpeg_command += ["-vf", sarge.shell_quote(",".join(rotate_params)), snapshot_path]
NameError: global name 'sarge' is not defined
```

**Comment by mark-hahn** [comment]
Turning off the image feature fixed it but I would really like to have images.

**Comment by tedder** [comment]
Did you install it through Octoprint? (eg not manually)

**Comment by shadycuz** [comment]
Mark I added the SMS feature, I'm traveling but I can look at it this
weekend. It must be a package dependency issue.

**Comment by tedder** [comment]
yeah, looks like sarge only shows up in the .py, not as a dependency.

**Comment by mark-hahn** [comment]
That was quick.  Thanks to all.  I assume I'll get a notification in octoprint when a new version is out.

**Comment by shadycuz** [comment]
We will finalize the PR soon and I will push a new package to pypy and
release a new version.

**Comment by shadycuz** [comment]
@mark-hahn @tedder The new version with the proper sarge package was pushed to pypi. I'm not sure if on update it will handle the new package dependency correctly. You may have to remove and reinstall Octoprint-Twilio. Re-open this issue if you have further problems =).

**Comment by mark-hahn** [comment]
thks
